### ISSUE TITLE
Adding local_subnet environment variable breaks container

### ISSUE THREAD

**Issue by prov3it** [jordanpotter/docker-wireguard#25]
Hi, when adding the local_subnet environment, the container can't be created because: 

```
Skipping IPv6 kill switch setup since IPv6 interface was not found
Allowing traffic to local subnet 192.168.X.0/8
**RTNETLINK answers: Invalid argument**
```

I understand that more information is needed, but i am not sure what i could do to debug.

im using:
```
version: "3"
services:
  wireguard:
    container_name: wireguard
    image: jordanpotter/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - /path/to/conf/mullvad.conf:/etc/wireguard/mullvad.conf
    restart: unless-stopped
    environment:
      - LOCAL_SUBNET=192.168.X.0/8
  curl:
    image: appropriate/curl
    command: http://httpbin.org/ip
    network_mode: service:wireguard
    depends_on:
      - wireguard
```
