### ISSUE TITLE
Cannot connect two services linked to wireguard

### ISSUE THREAD

**Issue by khataev** [jordanpotter/docker-wireguard#46]
I have two services behind wireguard (qbittorrent and jackett):

```yml
services:

  vpn:
    # https://github.com/jordanpotter/docker-wireguard
    container_name: vpn
    image: jordanpotter/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    environment:
      - LOCAL_SUBNETS=192.168.0.0/24
    ports:
      # jackett
      - 6001:9117
      # qBittorrent
      - 6002:6002
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /opt/wireguard/15R_FVZRJDYY_15.conf:/etc/wireguard/wg0.conf
      
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    depends_on:
      - vpn
    ...
    network_mode: service:vpn

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - vpn
    ...
    network_mode: service:vpn

  curl:
    container_name: curl
    image: curlimages/curl
    # command: ifconfig.io
    command: vpn:9117
    network_mode: service:vpn
    depends_on:
      - vpn
```

Jackett exposes port 9117, qbittorrent - 6002. These ports are accessible from host machine (WebUI) due to `LOCAL_SUBNETS` variable. But the problem is they can't communicate to each other. Previously, when I used `openvpn` image it worked, I could access jacket by referencing `http://vpn:9117` from qbittorrent service. Now this communication does not work. I added `curl` image to debug and it returns me the following error: `Could not resolve host: vpn`. 

What did I miss?
